### PR TITLE
Migrate steps to folders

### PR DESCRIPTION
**Pull request by remi**

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
> 494 files changed
image

**Comment by jeffmendoza** [comment]
I think this is going to be a merge-it-and-see-what-happened PR.

Do you have the clone instruction changes ready for https://cloud.google.com/ruby/getting-started/hello-world#download_app and the other pages?

**Comment by remi** [comment]
Working on the doc updates.  Went ahead and sent the pull to unblock refactoring of [PR17](https://github.com/GoogleCloudPlatform/getting-started-ruby/pull/17)

**Comment by jeffmendoza** [comment]
Cool, lets merge this. I see you have the doc changes ready as well.

**Pull request merged**
