### PR TITLE
New version of bookshelf for Google Container Engine.

### PR DESCRIPTION
**Pull request by jeffmendoza**
Mostly copied from step 6. Change default backend to Datastore.
Added kubernetes bookshelf-*.yaml files. Added Dockerfile. Removed
AppEngine app.yaml and worker.yaml.

### CODE REVIEW

**Comment by jeffmendoza** [comment]
@remi @bshaffer

**Comment by jeffmendoza** [comment]
@remi when you create your cluster, add 'userinfo-email' to the scopes

**Comment by jeffmendoza** [comment]
@remi Updated to log to stdout, logs are showing up in stackdriver now. I was getting a datastore error which is fixed by adding the above scope.

**Comment by remi** [comment]
LGTM! 👍

**Pull request merged**
