### PR TITLE
'update gcloud commands and remove additional app.yaml config'

### PR DESCRIPTION
**Pull request by JustinBeckwith**

### CODE REVIEW

**Comment by jeffmendoza** [comment]
Thanks Justin, We need to remove the relevant sections from https://cloud.google.com/ruby/getting-started/hello-world#managed_vms_config before merging this

**Comment by JustinBeckwith** [comment]
No problem - I'll take a look today

**Comment by bmclean** [comment]
@JustinBeckwith Why would we want to exclude the resources and automatic_scaling from the yaml files?

**Comment by JustinBeckwith** [comment]
We're looking to keep the getting started as simple as possible, especially in the hello world case.  Managed VMs work great with the default configuration, so that's where we want folks to start.

**Comment by bmclean** [comment]
@JustinBeckwith OK thanks, that makes sense.

**Comment by remi** [comment]
"resources" region tag is no longer references from Ruby documentation.  Merging

**Pull request merged**
