### PR TITLE
Don't lock Ruby version - always use latest

### PR DESCRIPTION
**Pull request by remi**
This solves a few problems:
1. During local development, users who have rbenv/rvm installed won't get errors if the specified .ruby-version is not installed
2. During deployment, the latest default Ruby version specified by the [Ruby runtime](https://github.com/GoogleCloudPlatform/ruby-docker/tree/master/appengine) will be used, helping our end-to-end tests ensure that the latest version always works

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
This doesn't feel right to me.  I wouldn't leave an app out there that has a floating version.  How do we know that a new release of Ruby won't break the app?  What do we expect customers to do?  Happy to be outvoted though.   @adamtanner, @dazuma, @bschaffer thoughts?

**Comment by broady** [comment]
It's better to know if a new release of Ruby breaks the app. It means
something, somewhere needs to be fixed.

**Comment by JustinBeckwith** [comment]
But this code is used as part of our getting started flow, and part of the interactive getting started.  If shouldn't ever be broken.  If this is broke, our getting started in the developer console is broke. 

If testing the latest version is the concern, that feels like something we could do via a simple nightly where we just delete the .ruby_version before running the test.  That test can focus specifically on the latest version.

**Comment by dazuma** [comment]
I'm agree with Justin here. These are customer-facing products that should not break, and we should specifically test them against new ruby versions _before_ releasing them to customers. If we want to test against latest, that's great, but it should happen separately without compromising the end-user product. (Note that the default ruby version in the runtime itself is also explicitly set in the base image; it doesn't just default to latest. And, similarly, we shouldn't rev the ruby in the base image without running end-to-end tests first.)

We also want to emphasize that .ruby-version is considered a best practice that we follow and support. I know there are currently pros and cons here with regard to deployment performance, but there are ways to fix that without compromising the integrity of the practice.

**Comment by remi** [comment]
Another variable to consider:

When I, personally, `git clone` and `cd 1-hello-world` and then `bundle install`, I get:

```
rbenv: version `2.2.3' is not installed
```

 *Ugh, I need to install 2.2.3... even though I have the latest stable version of Ruby...*

I frequently find this annoying for working on the getting started flow locally.  Plus it means that we have to manually bump our .ruby-version.  Getting started should work with Ruby 2.1.* or 2.2.* or 2.3.* AFAIK.  Also, why did we choose the `2.2.*` series to pin our tutorial to instead of `2.3.*`, which is the default for `ruby-docker`?

For testing, deleting the `.ruby-version` before running tests isn't correct because then it will run the tests for the latest stable version (per ruby-docker) but *not* the frozen version.  So we would need to update our E2E tests to run against multiple versions.  (We do this for unit tests but it's a bit much for E2E)

This has only ever caused me grief.

But it is correct that we should lock the version if we're to treat this like a user-facing product (especially for the interactive cloud shell tutorial).  I can send a new pull to bump to 2.3.0 instead and we will try to bump getting started every time ruby-docker is bumped?  Thoughts?

**Comment by adamtanner** [comment]
I think it's probably **a good idea** to delete the .ruby-version files and here's why:
*  I just briefly looked through the Getting Started docs and I didn't see any mention of rvm, rbenv, or the .ruby-version file support. Do we never tell users to install a version manager? Are there "minimum requirements" specified somewhere for what we expect the user to have installed on their dev machine?
*  If the user doesn't have rbenv/rvm installed the .ruby-version file is irrelevant for their local development. As far as I am aware (correct me if wrong) Bundler doesn't know anything about the .ruby-version file and has a separate way to specify the required Ruby version.
*  If the user doesn't have rbenv/rvm installed chances are they are using whatever Ruby came with their system which is unlikely to be the actual latest release. We'll have to be careful of the inverse problem, users with the system Ruby probably have Ruby versions that are multiple minor versions behind. (2.0.0p648 on my MBA running El Capitan)
* The hangup @remi mentions only affects users who happen to be using rbenv/rvm and probably know better than us what version of Ruby they want to run against. Forcing them to install another Ruby version, which can take several minutes, or change/delete the .ruby-version file, are just additional (albeit, small) blockers in trying out our platform.

Related: Can we add some mention of our .ruby-version support if it's not already present in the Getting Started docs? It's a useful feature that might be a deciding factor for some of our users (being able to specify JRuby for example).

**Comment by remi** [comment]
We will hold off on removing .ruby-version until ruby-docker has an E2E test that verifies getting-started-ruby/1-hello-world runs successfully so that we know updates to the ruby-docker default Ruby version do not break us

**Comment by remi** [comment]
I ran into this issue and sent a new PR to fix it: #67 

Locking these versions makes for a poor experience

**Pull request closed without merging**
