### PR TITLE
Update app.yaml to remove unneeded lines.

### PR DESCRIPTION
**Pull request by jeffmendoza**

### CODE REVIEW

**Comment by jonparrott** [comment]
Why not go ahead and remove resources and scaling settings? The python and node.js ones don't have this:

https://github.com/GoogleCloudPlatform/getting-started-python/blob/master/1-hello-world/app.yaml
https://github.com/GoogleCloudPlatform/nodejs-getting-started/blob/master/1-hello-world/app.yaml

**Comment by jeffmendoza** [comment]
We go through resources and scaling here: https://cloud.google.com/ruby/getting-started/hello-world#managed_vms_config

**Comment by jonparrott** [comment]
We used to as well, but that section of the docs as well as the code was
removed for the sake of simplicity. It's up to you, just wanted to make you
aware.

**Comment by jeffmendoza** [comment]
Ah ok, thanks. I'll bring it up with the team.

**Comment by JustinBeckwith** [comment]
:+1: I think we should simplify this here too.  @remi objections?

**Comment by jeffmendoza** [comment]
@JustinBeckwith Let's open another bug/issue to discuss removing resources/scaling from app.yaml

**Comment by JustinBeckwith** [comment]
sounds good

**Pull request merged**
